src/aurora/api/urls.py
from django.urls import include, path

from . import viewsets
from .router import AuroraRouter

app_name = "api"

router = AuroraRouter()
router.register(r"counter", viewsets.CounterViewSet)
router.register(r"field", viewsets.FlexFormFieldViewSet)
router.register(r"flatpage", viewsets.FlatPageViewSet)
router.register(r"form", viewsets.FlexFormViewSet)
router.register(r"formset", viewsets.FormSetViewSet)
router.register(r"registration", viewsets.RegistrationViewSet)
router.register(r"template", viewsets.TemplateViewSet)
router.register(r"template", viewsets.TemplateViewSet)
router.register(r"user", viewsets.UserViewSet)
router.register(r"validator", viewsets.ValidatorViewSet)
router.register(r"project", viewsets.ProjectViewSet)
router.register(r"record", viewsets.RecordViewSet)
router.register(r"organization", viewsets.OrganizationViewSet)
router.register(r"validator", viewsets.ValidatorViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("sys/", viewsets.system_info),
]

src/aurora/config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path, re_path

import adminactions.actions as actions
import debug_toolbar

from aurora.core.views import service_worker
from aurora.web.views.site import error_404

actions.add_to_site(admin.site)

handler404 = error_404

urlpatterns = [
    path(settings.DJANGO_ADMIN_URL, admin.site.urls),
    re_path(r"sax-\d*/", admin.site.urls),
    path("api/", include("aurora.api.urls", namespace="api")),
    path("", include("aurora.web.urls")),
    path("pages/", include("aurora.flatpages.urls")),
    path("charts/", include("aurora.counters.urls", namespace="charts")),
    path("social/", include("social_django.urls", namespace="social")),
    path("captcha/", include("captcha.urls")),
    path("hijack/", include("hijack.urls")),
    path("mdeditor/", include("mdeditor.urls")),
    path("i18n/", include("aurora.i18n.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path(r"serviceworker.js", service_worker, name="serviceworker"),
]

urlpatterns += i18n_patterns(
    path("", include("aurora.registration.urls")),
    path("", include("aurora.core.urls")),
)

src/aurora/counters/urls.py
from django.urls import path

from .views import index, MonthlyChartView, MonthlyDataView, project_index

app_name = "charts"

urlpatterns = [
    path("<str:org>/", index, name="index"),
    path("<str:org>/<int:prj>/", project_index, name="project-index"),
    path("<str:org>/<int:prj>/<int:registration>/monthly/", MonthlyChartView.as_view(), name="registration"),
    path("<str:org>/<int:prj>/data/<int:registration_id>/monthly/", MonthlyDataView.as_view(), name="monthly_data"),
]

src/aurora/counters/models.py
from collections import defaultdict
from datetime import datetime, timedelta

from django.db import models
from django.db.models import Count
from django.db.models.functions import ExtractHour, TruncDay
from django.utils.functional import cached_property

from aurora.registration.models import Record, Registration


class CounterManager(models.Manager):
    def collect(self, *, registrations=None):
        result = {"registration": 0, "records": 0, "days": 0, "details": {}}
        today = datetime.today()
        yesterday = datetime.combine(today - timedelta(days=1), datetime.max.time())
        selection = Registration.objects.filter(archived=False)

        def annotate(qs):
            return (
                qs.annotate(hour=ExtractHour("timestamp"), day=TruncDay("timestamp"))
                .values("day", "hour")
                .annotate(c=Count("id"))
                .order_by("day", "hour")
            )

        if registrations:
            selection = selection.filter(id__in=registrations)
        querysets = []
        for registration in selection:
            result["registration"] += 1
            result["details"][registration.slug] = {"range": [], "days": 0}
            latest = Counter.objects.filter(registration=registration).order_by("-day").first()
            if latest:
                latest = latest.day + timedelta(days=1)
            else:
                latest = datetime.min
            qs = annotate(Record.objects.filter(registration=registration, timestamp__range=(latest, yesterday)))
            today_data = annotate(Record.objects.filter(registration=registration, timestamp__date=today))
            querysets.append(qs)
            counter = defaultdict(lambda: {"records": 0, "extra": {}})
            for q in [qs, today_data]:
                for match in q.all():
                    counter[match["day"]]["records"] += match["c"]
                    counter[match["day"]]["extra"][match["hour"]] = match["c"]
                    result["days"] += 1
            for day, values in counter.items():
                result["records"] += values["records"]
                result["details"][registration.slug]["days"] += 1
                if today.date() == day.date():
                    Counter.objects.update_or_create(
                        registration=registration,
                        day=day,
                        defaults={
                            "records": values["records"],
                            "details": {"hours": values["extra"]},
                        },
                    )
                else:
                    Counter.objects.get_or_create(
                        registration=registration,
                        day=day,
                        defaults={
                            "records": values["records"],
                            "details": {"hours": values["extra"]},
                        },
                    )
        return querysets, result


class Counter(models.Model):
    registration = models.ForeignKey(Registration, on_delete=models.CASCADE, related_name="counters")
    day = models.DateField(blank=True, null=True, db_index=True)
    records = models.IntegerField(default=0, blank=True, null=True)
    details = models.JSONField(default=dict, blank=True)

    objects = CounterManager()

    class Meta:
        unique_together = ("registration", "day")
        get_latest_by = "day"
        ordering = ("-day",)

    def __str__(self):
        try:
            return f"{self.registration} {self.day}"
        except Exception:
            return f"Counter #{self.pk}"

    @cached_property
    def hourly(self):
        return [self.details["hours"].get(str(x), 0) for x in range(23)]

src/aurora/counters/forms.py
from django import forms

from aurora.registration.models import Registration


class ChartForm(forms.Form):
    registration = forms.ModelChoiceField(Registration.objects.all())

src/aurora/counters/views.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views import View

from aurora.core.models import Organization, Project
from aurora.core.utils import get_session_id, last_day_of_month, render
from aurora.counters.models import Counter
from aurora.registration.models import Registration

User = get_user_model()


@login_required()
def index(request, org):
    o: Organization = Organization.objects.get(slug=org)
    if not request.user.has_perm("counters.view_counter", o):
        raise PermissionDenied("----")
    context = {"organization": o, "projects": o.projects.filter(members__user=request.user)}
    return render(request, "counters/index.html", context)


@login_required()
def project_index(request, org, prj):
    o: Organization = Organization.objects.get(slug=org)
    p: Project = Project.objects.get(organization=o, pk=prj)
    if not request.user.has_perm("counters.view_counter", p):
        raise PermissionDenied("----")
    context = {"project": p, "registrations": p.registrations.filter(members__user=request.user)}
    return render(request, "counters/project.html", context)


class ChartView(UserPassesTestMixin, View):
    permission_denied_message = "----"
    login_url = "/login/"

    def test_func(self):
        return self.request.user.is_authenticated

    def get_registration(self, request, org, prj, reg_pk) -> Registration:
        reg = get_object_or_404(Registration, project__organization__slug=org, project_id=prj, id=reg_pk)
        if not request.user.has_perm("counters.view_counter", reg):
            raise PermissionDenied("----")
        return reg

    def handle_no_permission(self):
        return HttpResponseRedirect("/")


class MonthlyDataView(ChartView):
    def get(self, request, org, prj, registration_id):
        registration = self.get_registration(request, org, prj, registration_id)
        qs = Counter.objects.filter(registration_id=registration_id).order_by("day")
        param_month = request.GET.get("m", None)
        total = 0
        if param_month:
            date = datetime.strptime(param_month, "%Y-%m-%d")
        else:
            date = timezone.now()

        qs = qs.filter(day__month=date.month)
        last_day = last_day_of_month(date)
        days = list(range(1, 1 + last_day.day))
        labels = [last_day.replace(day=d).strftime("%-d, %a") for d in days]
        values = {}
        for d in range(1, last_day.day + 1):
            dt = date.replace(day=d).date()
            values[dt] = {"total": 0, "pk": 0}

        for record in qs.all():
            values[record.day] = {"total": record.records, "pk": record.pk}
            total += record.records

        if not labels:
            labels = [d.strftime("%-d, %a") for d in values.keys()]
        period = date.strftime("%B %Y")
        data = {
            "datapoints": qs.all().count(),
            "label": f"{registration} {period}",
            "day": date.strftime("%Y-%m-%d"),
            "total": total,
            "labels": labels,
            "data": list(values.values()),
        }
        response = JsonResponse(data)
        # response["Cache-Control"] = "max-age=315360000"
        # response["Last-Modified"] = "max-age=315360000"
        # response["ETag"] = etag
        return response


def daily_data(request, registration, record):
    pass


class MonthlyChartView(ChartView):
    def get(self, request, org, prj, registration):
        reg: Registration = self.get_registration(request, org, prj, registration)
        first: [Counter] = reg.counters.first()
        latest: [Counter] = reg.counters.last()
        if not latest:
            latest = timezone.now()
        context = {
            "registration": reg,
            "first": first,
            "latest": latest,
            "token": get_session_id(),
            # "years": range(first.day.year, latest.day.year)
        }
        return render(request, "counters/chart_month.html", context)

src/aurora/counters/templates/counters/chart_base.html
{% extends "base.html" %}{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static "counters/counters.css" %}">
    <script src="{% static "admin/js/vendor/jquery/jquery.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/2.0.0/chartjs-plugin-datalabels.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-annotation/1.4.0/chartjs-plugin-annotation.min.js"
            integrity="sha512-HrwQrg8S/xLPE6Qwe7XOghA/FOxX+tuVF4TxbvS73/zKJSs/b1gVl/P4MsdfTFWYFYg/ISVNYIINcg35Xvr6QQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock %}

{% block body %}
    <h1 class="text-lg mb-20">
        <a href="{% url "charts:index" registration.project.organization.slug %}">{{ registration.project.organization }}</a> /
        <a href="{% url "charts:project-index" registration.project.organization.slug registration.project.pk %}">{{ registration.project }}</a> /
        {{ registration }}</h1>

    <div class="min-h-screen flex w-wull bg-gray-100 pb-10 charting">
        {% block info %}
            <div class="w-full m-20 lg:w-1/2 mt-5">
                <h1 class="text-lg">{{ registration }}</h1>
                <div><strong>Started on : </strong>{{ registration.start }}</div>
                <div><strong>Until: </strong>{{ registration.end|default_if_none:"Running" }}</div>
                <div><strong>Status: </strong>{% if registration.active %}Active{% else %}Paused{% endif %}</div>
                {% block chart %}
                    <div class="my-5">
                        <button class="button" id="prev"><<</button>
                        <button class="button" id="next"> >></button>
                    </div>
                    <div class="chart-container">
                        <canvas id="myChart" style="width: 100%;height: 100%"></canvas>
                    </div>
                {% endblock %}
            </div>
        {% endblock %}
        {% block data %}{% endblock %}
    </div>
{% endblock %}

src/aurora/counters/templates/counters/chart_month.html
{% extends "counters/chart_base.html" %}{% load static %}
{% block data %}
    <script id="counters" data-registration={{ registration.pk }} data-token="{{ token }}"
            data-url="{% url "charts:monthly_data" registration.project.organization.slug registration.project.pk registration.pk %}"
            src="{% static "counters/monthly.min.js" %}"></script>
{% endblock %}

src/aurora/counters/templates/counters/index.html
{% extends "base.html" %}{% load static %}
{% block body %}

    <div class="min-h-screen flex w-wull bg-gray-100 pb-10">
        <div class="w-full m-20 lg:w-1/2 mt-5">
            <h1 class="text-lg mb-20">{{ organization }}</h1>
        <ul>
            {% for project in projects %}
                <li><a href="{% url "charts:project-index" organization.slug project.pk %}">{{ project }}</a></li>
            {% endfor %}
        </ul>
        </div>
    </div>

{% endblock body %}

src/aurora/counters/templates/counters/project.html
{% extends "base.html" %}{% load static %}
{% block body %}

    <div class="min-h-screen flex w-wull bg-gray-100 pb-10">
        <div class="w-full m-20 lg:w-1/2 mt-5">
            <h1 class="text-lg mb-20">
                <a href="{% url "charts:index" project.organization.slug %}">{{ project.organization }}</a> / {{ project }}</h1>
        <ul>
            {% for reg in registrations.all %}
                <li><a href="{% url "charts:registration" project.organization.slug project.pk reg.pk %}">{{ reg }}</a></li>
            {% endfor %}
        </ul>
        </div>
    </div>

{% endblock body %}